# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmdBCe3AOGqA_e4Ccj-AtgQ-yHJdq4Dw
"""

from flask import Flask, request, jsonify, render_template

import numpy as np
import pickle
import os

#app name
app = Flask(__name__,template_folder='templates')

model=pickle.load(open(Loan_model.pkl','rb'))

#home page
@app.route('/')
def home():
  return render_template(index.html')

#predict the result and return it
@app.route('/predict',methods=['POST'])
def predict():
    '''
    For rendering results on HTML GUI
    '''
    int_features = [int(x) for x in request.form.values()]
    final_features = pd.DataFrame([int_features], columns=['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Property_Area'])
    prediction = model.predict(final_features)
    if 	prediction==0:
	      pred="Rejected"
    else:
        pred="Approved" 

   

    return render_template('index.html', prediction_text='Loan application is  {}'.format(prediction))

if __name__ == "__main__":
    app.run(debug=True)